### ISSUE TITLE
Cannot read HEVC images (HEIF)

### ISSUE THREAD

**Issue by nathanielcwm** [olgamiller/SSTVEncoder2#10] opened 2022-01-19 16:07 UTC
Upon attempting to use a HEIF file it errors stating:

```
Image Loading Error

Resetting to invalid mark.
```

The images otherwise display normally in the selection.

Android 11, Samsung S10, HEIF files from stock camera app.

**Comment by olgamiller** [comment] 2023-03-04 15:56
Thanks for reporting the issue. Unfortunately, I could not reproduce it so far (HEIF images loaded successfully on Android 11 and Android 12). May I ask you to send me such an image?

**Comment by nathanielcwm** [comment] 2023-03-04 23:32
![20230305_072559.jpg](https://user-images.githubusercontent.com/22572406/222933376-ff898f3d-a23d-43c7-b334-9f54bc4be50a.jpg)

File extension changed to get around GitHub limits (original file extension is heic)

Tested with Android 13 and I can still repro

**Comment by olgamiller** [comment] 2023-03-05 13:47
Thank you for the image. - I got the same error.
In version 2.8 it should be fixed.

**Closed as completed** 2023-08-27 11:09 UTC
